variables:
- name: ReleaseEnvironmentName
  value: DEV
- name: WebAppPrefix
  value: mon-dev-api-calc
- name: ResourceGroup
  value: $(WebAppPrefix)-rg
- name: FunctionAppDomain
  value: azurewebsites.net
- name: aspTier
  value: Standard
- name: aspInstances
  value: 2
- name: aspSize
  value: 2
- name: ExceptionCountThreshold
  value: 10
- name: MemoryPercentageThreshold
  value: 75
- name: CPUPercentageThreshold
  value: 75
- name: EnableAzureMonitorAlerting
  value: true
- name: FunctionAppName
  value: $(WebAppPrefix)-fa
- name: ApplicationName
  value: monc-api-calc
- name: apimLoggerName
  value: CALC-logger
- name: apimProductName
  value: CALC
- name: apimApiName
  value: Calculator
- name: SubscriptionPosturi
  value: https://$(FunctionAppName).$(FunctionAppDomain)/api/subscription
- name: appSharedResourceGroup
  value: mon-dev-app-sharedresources-rg
- name: appSharedStorageAccountName
  value: mondevappsharedstr